// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaineisSolares.Models;

namespace PaineisSolares.Migrations
{
    [DbContext(typeof(PaineisSolaresContext))]
    [Migration("20190715224820_atualizacao")]
    partial class atualizacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PaineisSolares.Models.Ambiente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Ambiente");
                });

            modelBuilder.Entity("PaineisSolares.Models.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AmbienteId");

                    b.Property<double>("ConsumoTotal");

                    b.Property<double>("ConsumoTotalPorDia");

                    b.Property<double>("ConsumoUnitario");

                    b.Property<string>("Descricao");

                    b.Property<int>("HorasDeUso");

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("Equipamento");
                });

            modelBuilder.Entity("PaineisSolares.Models.Equipamento", b =>
                {
                    b.HasOne("PaineisSolares.Models.Ambiente", "Ambiente")
                        .WithMany("Equipamentos")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
